CREATE TABLE IF NOT EXISTS experiments (
 id INTEGER PRIMARY KEY,
 experiment_id INTEGER NOT NULL,
 cx TEXT NOT NULL,
 fun TEXT NOT NULL,
 dim INTEGER NOT NULL,
 date TEXT NOT NULL,
 gen INTEGER NOT NULL,
 nevals INTEGER NOT NULL,
 min REAL NOT NULL,
 max REAL NOT NULL,
 avg REAL NOT NULL,
 std REAL NOT NULL,
 best TEXT NOT NULL,
 config TEXT NOT NULL
);
